### ISSUE TITLE
Unable to use cloudfront 

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-cms#280]
Hi,
I tried to configured cloudfront and tried to use with camaleon-cms by configuring "config.action_controller.asset_host " inconfig/environments/production.rb file, but tinyMCE and sidebar  etc icons  are missing  after cloudfront configuration, please let me know how I can use cloudfront along with camaleon-cms.

**Comment by owen2345** [comment]
@mazharoddin 
could you please send me a link where can I see the manual to use cloudfront? to reproduce the problem.
sorry, I didn't use cloudfront.

**Comment by mazharoddin** [comment]
Hi,
I followed this guide to setup cloudfront https://www.happybearsoftware.com/use-cloudfront-and-the-rails-asset-pipeline-to-speed-up-your-app.html
This doc is much detailed, but actually to enable cloudfront we just need to add "config.action_controller.asset_host = 'your-dist-url.cloudfront.com'" in production.rb file after setting up new distribution with amazon cloudfront service.
Please feel free to ask for any further info if you need.

**Comment by raulanatol** [comment]
Hi guys!

@mazharoddin have you tried to change the AWS S3 bucket endpoint value?

@owen2345 to use cloudfront only is necessary change the image url (if cloudfront is correctly configured on AWS).
Example:
- Image url with S3: https://bucket_name.s3.amazonaws.com/example.png
- Image url with cloudfront: https://cloudfront_id.cloudfront.net/example.png

Regards.

**Comment by raulanatol** [comment]
Maybe a possible solution something like this:

![cloudfront](https://cloud.githubusercontent.com/assets/2389019/12322148/44cf1224-baaa-11e5-99a2-00623150c0af.png)

**Comment by mazharoddin** [comment]
Hi Raul,
Yes, I tried to change the S3 endpoint, but still its not working.
Two use cases need to be considered here  , one is enabling cloudfront for static assets like as I mentioned in this issue.
Second use case is create cloudfront distribution with S3 end-point and then use along with for S3 images or videos the way carrierwave uses(issue#291). 
Yes, above solution would be good for S3 endpoint cloudfront distribution, and static asset  cloudfront distribution can be configured at config/environments/production.rb file as below.
````
config.action_controller.asset_host = "xxx.cloudfront.net"

**Comment by mazharoddin** [comment]
Hi @owen2345, please look into this issue if you got some time, images from S3 bucket taking lot of time to load without cloudfront CDN.

**Comment by owen2345** [comment]
I am sorry friends!
I forget this issue, I am working in this and using the screenshot of @raulanatol 
Regards,

**Comment by owen2345** [comment]
Done and Tested!
![2016-04-27_1812](https://cloud.githubusercontent.com/assets/1148415/14869748/a354fa5c-0ca3-11e6-9468-d4886a6b0a0c.png)
![screen shot 2016-04-27 at 6 11 26 pm](https://cloud.githubusercontent.com/assets/1148415/14869749/a356a604-0ca3-11e6-833a-2282f3e600e2.png)

@raulanatol Thank you for the picture, it helps me a lot!

**Comment by mazharoddin** [comment]
Thank you ...

**Comment by owen2345** [comment]
@mazharoddin 
did you tried again? because tinymce was replaced to use a rails gem

**Comment by mazharoddin** [comment]
Hi @owen2345, 
No I haven't tested yet, but we need to use two cloudfront CDN urls to achieve maximum performance, one URL with S3 bucket as end point so that it can be synced directly in amazon console itself..another cloudfront url with sitename as endpoint so that it can be used to load images/css/js etc. for static content (we can have multiple cloudfront url's with different end points for static content).

So above URL mentioned in screen shot should have S3 bucket as end point , so that it can load images directly.

**Comment by mazharoddin** [comment]
Hi @owen2345,

Its working perfectly for S3 bucket end point.. thanks...
I added another cloudfront distribution URL  with site hostname as end point in config/environments/production.rb to serve static content, now I am not seeing issue with tinyMCE icons..but other icons are still missing, please find below attachment for reference.
![screen shot 2016-04-29 at 10 50 34](https://cloud.githubusercontent.com/assets/6102465/14908698/3f0274f2-0df8-11e6-995b-e8c7e86c9341.png)
Please ignore my comment on adding one more cloudfront URL link at configuration tab, it's not required because we can add it at config/environments directory. Thanks.

**Comment by owen2345** [comment]
@mazharoddin 
For those fonts, please investigate the gem "font-awesome-rails" with Cloudfront which is used by camaleon cms.
I think the solution is like this:
https://derikulous.github.io/year/11/16/how-to-fontawesome/
Regards,

**Comment by mazharoddin** [comment]
Sure @owen2345, 
I am closing this issue because  originally reported issue is fixed ..thanks

**Comment by owen2345** [comment]
@mazharoddin 
I you solve this situation, please share here how did you resolved it.

**Comment by mazharoddin** [comment]
No, I haven't solved the font awesome issue yet, I mean the original issue of tinyMCE issue is resolved and I am able to add cloudfront URL for S3 bucket.. ..I will try and update here if I solve fontawesome issue.

**Comment by mazharoddin** [comment]
Hi @owen2345,
Above solution in link https://derikulous.github.io/year/11/16/how-to-fontawesome/ didn't worked for me.
I could able to fix the issue by following this suggestion (stackoverflow.com/questions/33003567/rails-assets-cloudfront-fontawesome-cors)

But I had to change Nginx config as below.
 location ~ "/assets/.*-[0-9a-f]{32}.*" {
        add_header Access-Control-Allow-Origin *;
        gzip_static on;
}

With this change I could able to resolve  fontawesome issue...site is super fast now :) ..thank you..

**Comment by owen2345** [comment]
Great!
Thanks for sharing.
