### ISSUE TITLE
Paginate Not Working when custom routes

### ISSUE THREAD

**Issue by Uysim** [owen2345/camaleon-cms#374]
when I custom routes to will paginate will_pagination will return link http://host.com/post?page=1 as the @posts collection is Post class

**Comment by owen2345** [comment]
Hey @Uysim 
could you please tell me how to generate the problem? and how did you change the routes?

**Comment by Uysim** [comment]
I did change routes follow the document. But when when I have post type example like blog. @posts = current_site.the_post_type('blog').the_post. so the url should be http://host.com/blog?page=1 but will paginate will return http://host.com/post?page=1 because @posts collection have class Post

**Comment by owen2345** [comment]
@Uysim 
it is a little complex to reproduce it, could you please send me a demo project with that problem?

**Comment by pannsamnang** [comment]
@owen2345  Your document url is also have problem like this too. [](http://camaleon.tuzitio.com/post.html?page=2)

**Comment by owen2345** [comment]
Ohhh I understand, thank you for the report. Checking...

**Comment by owen2345** [comment]
Fixed!

**Comment by pannsamnang** [comment]
@owen2345  You said it was fixed already, but when I update the gem file and try to use user cama_do_pagination I still have that problem. After I custom the post type route.

**Comment by owen2345** [comment]
it is strange, because here is working well:
http://camaleon.tuzitio.com/docs.html
could you please give more details?

**Comment by pannsamnang** [comment]
@owen2345  It is working. I still have that problem because I still use the custom route.

**Comment by owen2345** [comment]
I think the problem is in your custom route and not in the CMS
