### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by sahilchopra** [owen2345/camaleon-cms#487]
rails c is not working.

.rvm/gems/ruby-2.3.0@cms/gems/actionpack-5.0.0.1/lib/action_controller/test_case.rb:49:in `initialize': wrong number of arguments (given 0, expected 2) (ArgumentError)
	from /home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.0@cms/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:41:in `new'
	from /home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.0@cms/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:41:in `block in controller'
	from /home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.0@cms/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:40:in `tap'
	from /home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.0@cms/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:40:in `controller'
	from /home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.0@cms/gems/draper-2.1.0/lib/draper/view_context/build_strategy.rb:30:in `call'

**Comment by mazharoddin** [comment]
hi,
As per @owen2345,  rails5 issue already got fixed in #485, try with latest version. thanks.

**Comment by sahilchopra** [comment]
I am already using latest version '    camaleon_cms (2.3.3)'

**Comment by mazharoddin** [comment]
ok, I mean latest Git master branch version...even if that didn't fix then there may be some other issue.

**Comment by owen2345** [comment]
Hi @sahilchopra,
I had the same problem and I fixed with bundle update and now it works well:

![screen shot 2016-09-12 at 09 21 31](https://cloud.githubusercontent.com/assets/1148415/18437311/57f92054-78ca-11e6-823c-4ac5f1e1dfa3.png)

**Comment by ferrisoxide** [comment]
A simple `bundle update` didn't fix the issue on my OS X box, but adding the following to the Gemfile did:

```
gem 'draper', github: 'audionerd/draper', branch: 'rails5'
```

Source: http://stackoverflow.com/questions/38716309/rails-5-upgrade-actionpack-5-0-0-lib-action-controller-test-case-rb49in-in
