### ISSUE TITLE
warning: already initialized constant JSON::*

### ISSUE THREAD

**Issue by hazemtaha** [owen2345/camaleon-cms#596]
i've been getting this warning with anything related to camaleon project in the command line rake tasks, rails generators, rails server, etc...

> /home/kan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/version.rb:4: warning: already initialized constant JSON::VERSION
/home/kan/.rvm/gems/ruby-2.3.0@cpc/gems/json-2.0.3/lib/json/version.rb:4: warning: previous definition of VERSION was here
/home/kan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/version.rb:5: warning: already initialized constant JSON::VERSION_ARRAY
/home/kan/.rvm/gems/ruby-2.3.0@cpc/gems/json-2.0.3/lib/json/version.rb:5: warning: previous definition of VERSION_ARRAY was here
/home/kan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/version.rb:6: warning: already initialized constant JSON::VERSION_MAJOR
/home/kan/.rvm/gems/ruby-2.3.0@cpc/gems/json-2.0.3/lib/json/version.rb:6: warning: previous definition of VERSION_MAJOR was here
/home/kan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/version.rb:7: warning: already initialized constant JSON::VERSION_MINOR
/home/kan/.rvm/gems/ruby-2.3.0@cpc/gems/json-2.0.3/lib/json/version.rb:7: warning: previous definition of VERSION_MINOR was here
/home/kan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/version.rb:8: warning: already initialized constant JSON::VERSION_BUILD
/home/kan/.rvm/gems/ruby-2.3.0@cpc/gems/json-2.0.3/lib/json/version.rb:8: warning: previous definition of VERSION_BUILD was here
/home/kan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:100: warning: already initialized constant JSON::NaN
/home/kan/.rvm/gems/ruby-2.3.0@cpc/gems/json-2.0.3/lib/json/common.rb:100: warning: previous definition of NaN was here
/home/kan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:102: warning: already initialized constant JSON::Infinity
/home/kan/.rvm/gems/ruby-2.3.0@cpc/gems/json-2.0.3/lib/json/common.rb:102: warning: previous definition of Infinity was here
/home/kan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:104: warning: already initialized constant JSON::MinusInfinity
/home/kan/.rvm/gems/ruby-2.3.0@cpc/gems/json-2.0.3/lib/json/common.rb:104: warning: previous definition of MinusInfinity was here
/home/kan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:129: warning: already initialized constant JSON::UnparserError
/home/kan/.rvm/gems/ruby-2.3.0@cpc/gems/json-2.0.3/lib/json/common.rb:129: warning: previous definition of UnparserError was here

and every time i try to run the rails server i get this additional warning 

> Expected string default value for '--decorator'; got true (boolean)
Expected string default value for '--decorator'; got true (boolean)
Expected string default value for '--serializer'; got true (boolean)

i'm using rails 5.0.2 and ruby 2.3.0 and camaleon 2.4.3.2

**Comment by owen2345** [comment]
Fixed JSON warnings, but I could not reproduce the decorator warning.

**Comment by tostasqb** [comment]
`bundle clean --force` may solve this issue

**Comment by owen2345** [comment]
yeah, I added 1 version ago a fix to avoid those warnings, but it generated error for rails 4 (I reverted it back until to find another fix)

**Comment by tostasqb** [comment]
This still happened for me with rails 5, a `bundle clean --force` and a `bundle` then again fixed it for me.

**Comment by owen2345** [comment]
great!
